### PR TITLE
Feature/openfin target

### PR DESCRIPTION
**Pull request by rdepena**
@datamadic @whyn07m3

### CODE REVIEW

**Comment by andreGarvin** [comment]
You might want to use `ts-loader` for bundle the typescript files instead of waiting for compile and then bundle. @rdepena 

```js
const { resolve, dirname } = require('path')

const entryPath = resolve(`${__dirname}/src`)
const outPath = resolve(`${ __dirname }/dist`)
module.exports = {
    entry: resolve(entryPath, '/main.ts'),
    output: {
        path: outPath,
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                include: entryPath,
                loader: 'ts-loader'
            }
        ]
    }
}
```

**Comment by rdepena** [comment]
@andreGarvin would I have the ability to have both the bundle and the ts out folder. The module should work both in node and OpenFin.

**Comment by andreGarvin** [comment]
Yes in the `dist` folder it will have the `out` folder insides, I believe the `ts-loader` for webpack is the `tsc` under the hood, so it looks at the `tsconfig` for guidance __webpack__ is not steering the wheel entirely.

**Comment by andreGarvin** [comment]
@rdepena I see that you have the entryPath to `./out/src/index.js` so are you going to compile and then bundle? Is there a reason you are using ts-loader which bundles and gives you the `out` inside of the `dist` folder ?

**Pull request merged**
